version: '3.8'

services:
  api-whisperer-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      # Mount demo into the container
      - ./content:/app/assets/content:ro
      - ./config.json:/app/assets/config.json:ro
